mpc_arm_controller:
  type: "crane_x7_mpc/mpc_nodelet"
  publish_rate: 1000
  joints:
    - crane_x7_shoulder_fixed_part_pan_joint
    - crane_x7_shoulder_revolute_part_tilt_joint
    - crane_x7_upper_arm_revolute_part_twist_joint
    - crane_x7_upper_arm_revolute_part_rotate_joint
    - crane_x7_lower_arm_fixed_part_joint
    - crane_x7_lower_arm_revolute_part_joint
    - crane_x7_wrist_joint
  constraints:
    goal_time: 0.0
    stopped_velocity_tolerance: 1.0